"dataset_name": "kvasir_seg"

"model_name": "unet"
"model_parameters":
    "in_channels": 1
    "out_channels": 2

"optimizer_name": "adam"
"optimizer_parameters":
    "lr": 1.0e-4
    "eps": 1.0e-8

"loss_name": "dice"
"loss_parameters":

"epochs": 100
"batch_size": 16
